# Generated by Django 4.1.7 on 2023-03-11 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='item1',
            new_name='item',
        ),
    ]
